// <auto-generated />
using System;
using HbCrm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HbCrm.Data.Migrations
{
    [DbContext(typeof(HbCrmContext))]
    [Migration("20191021084429_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<string>("Email");

                    b.Property<string>("Guid");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("NickName");

                    b.Property<string>("Password");

                    b.Property<string>("QQ");

                    b.Property<string>("UserName");

                    b.Property<string>("WeChar");

                    b.HasKey("Id");

                    b.ToTable("sys_admin");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysAdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdminId");

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_adminrole");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("RoleName");

                    b.Property<string>("RoleRemark");

                    b.Property<int>("RoleStatus");

                    b.HasKey("Id");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysFunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<string>("FunctionName");

                    b.Property<string>("FunctionRemark");

                    b.Property<int>("FunctionSort");

                    b.Property<string>("FunctionSystermName");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("MenuId");

                    b.HasKey("Id");

                    b.ToTable("sys_function");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysFunctionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<int>("FunctionId");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_functionrole");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("MenuIcon");

                    b.Property<string>("MenuName");

                    b.Property<string>("MenuRemark");

                    b.Property<int>("MenuSort");

                    b.Property<string>("MenuSystermName");

                    b.Property<string>("MenuUrl");

                    b.Property<int>("ParentMenuId");

                    b.HasKey("Id");

                    b.ToTable("sys_menu");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysMenuRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName");

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("MenuId");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_menurole");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysAdminRole", b =>
                {
                    b.HasOne("HbCrm.Core.Domain.Admin.SysAdmin", "SysAdmin")
                        .WithMany("AdminRoles")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HbCrm.Core.Domain.Admin.SysRole", "SysRole")
                        .WithMany("AdminRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysFunctionRole", b =>
                {
                    b.HasOne("HbCrm.Core.Domain.Authorize.SysFunction", "SysFunction")
                        .WithMany("FunctionRoles")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HbCrm.Core.Domain.Admin.SysRole", "SysRole")
                        .WithMany("FunctionRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysMenuRole", b =>
                {
                    b.HasOne("HbCrm.Core.Domain.Authorize.SysMenu", "SysMenu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HbCrm.Core.Domain.Admin.SysRole", "SysRole")
                        .WithMany("MenuRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
