// <auto-generated />
using System;
using HbCrm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HbCrm.Data.Migrations
{
    [DbContext(typeof(HbCrmContext))]
    [Migration("20191022021302_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50);

                    b.Property<string>("NickName")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("QQ")
                        .HasMaxLength(50);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("WeChar")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("sys_admin");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysAdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdminId");

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_adminrole");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RoleRemark")
                        .HasMaxLength(255);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("MenuIcon")
                        .HasMaxLength(50);

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MenuRemark")
                        .HasMaxLength(255);

                    b.Property<int>("MenuSort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("MenuSystermName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("MenuType");

                    b.Property<string>("MenuUrl");

                    b.Property<int>("ParentMenuId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("sys_menu");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysMenuRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateBy");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CreatebyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LastUpdateBy");

                    b.Property<string>("LastUpdateByName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("MenuId");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_menurole");
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Admin.SysAdminRole", b =>
                {
                    b.HasOne("HbCrm.Core.Domain.Admin.SysAdmin", "SysAdmin")
                        .WithMany("AdminRoles")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HbCrm.Core.Domain.Admin.SysRole", "SysRole")
                        .WithMany("AdminRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HbCrm.Core.Domain.Authorize.SysMenuRole", b =>
                {
                    b.HasOne("HbCrm.Core.Domain.Authorize.SysMenu", "SysMenu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HbCrm.Core.Domain.Admin.SysRole", "SysRole")
                        .WithMany("MenuRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
